/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ControladoraGeneral.ControladoraGneral;
import DiagramaDeClases.Ciudad;
import DiagramaDeClases.Cliente;
import DiagramaDeClases.Edificio;
import DiagramaDeClases.Propiedad;
import DiagramaDeClases.TipoEmpleado;
import DiagramaDeClases.TipoPropiedad;
import Global.BloquearBotones;
import Global.BloquearTexto;
import Global.Habilitarbotonoes;
import Global.Limpiador;
import Global.LimpiarTabla;
import Global.habilitarTexto;
import java.awt.event.ItemEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matia
 */





public class GestionPropiedad extends javax.swing.JInternalFrame {
    ControladoraGneral control ;
    Limpiador limpia = new Limpiador();
    BloquearTexto block = new BloquearTexto();
    BloquearBotones boto = new BloquearBotones();
    Habilitarbotonoes boton = new Habilitarbotonoes();
    habilitarTexto text = new habilitarTexto();
    LimpiarTabla tabla = new LimpiarTabla();
    
    /**
     * Creates new form GestionPropiedad
     */
    
   
    
    
    
    
    
    public GestionPropiedad(ControladoraGneral control) {
        initComponents();
        this.CargarTablaPropiedad(control.getContraladoraPropiedad().getpropiedad());
        this.cargarCombox(control.getContraladoraPropiedad().gettipopropiedad(),cbotipropiedad);
        this.cargarCombox(control.getContraladoraPropiedad().getcliente(),departamentoCliente);
        this.cargarCombox(control.getControladoraEdificios().getEdificio(),cbotipoedificios);
        this.cargarCombox(control.getControladoreCiudad().getciudad(), cbociudad);
        //this.cargarCombox(control.getContraladoraPropiedad().getpropiedad(), jcomboxestado);
        txtmetrocuadradocomun.setVisible(false);
        txtmetrocuadradopropio.setVisible(false);
        lblmetrocuadradocomun.setVisible(false);
        lblmetrocuadradopropio.setVisible(false);
        
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablepropiedad = new javax.swing.JTable();
        panelLimpadorCliente = new javax.swing.JPanel();
        txtnombrePropiedads = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        lbldireccion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumerodepiso = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbotipropiedad = new javax.swing.JComboBox<>();
        lblnombre1 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JLabel();
        departamentoCliente = new javax.swing.JComboBox<>();
        txtmetrocuadradocomun = new javax.swing.JTextField();
        lblmetrocuadradocomun = new javax.swing.JLabel();
        lblmetrocuadradopropio = new javax.swing.JLabel();
        txtmetrocuadradopropio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbotipoedificios = new javax.swing.JComboBox<>();
        txtestados = new javax.swing.JTextField();
        lblciudad = new javax.swing.JLabel();
        cbociudad = new javax.swing.JComboBox<>();
        panelComanpropiedad = new javax.swing.JPanel();
        btnmodificarpropiedad = new javax.swing.JButton();
        btnborrarpropiedad = new javax.swing.JButton();
        bntagregarpropiedad = new javax.swing.JButton();
        panelcompropiedad = new javax.swing.JPanel();
        btnguardadPropiedad = new javax.swing.JButton();
        btnLimpiarPropiedad = new javax.swing.JButton();
        btnCancelarPropiedad = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(222, 117, 11));

        jtablepropiedad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtablepropiedad);

        panelLimpadorCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtnombrePropiedads.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrePropiedadsKeyTyped(evt);
            }
        });

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });

        lbldireccion.setText("Direccion:");

        jLabel2.setText("Numero de piso:");

        txtnumerodepiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumerodepisoKeyTyped(evt);
            }
        });

        txtUsuario.setText("Estado:");

        jLabel1.setText("Tipo Propiedad:");

        cbotipropiedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", " ", " " }));
        cbotipropiedad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbotipropiedadItemStateChanged(evt);
            }
        });
        cbotipropiedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbotipropiedadMouseClicked(evt);
            }
        });
        cbotipropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipropiedadActionPerformed(evt);
            }
        });

        lblnombre1.setText("Nombre:");

        txtUsuario1.setText("Cliente:");

        departamentoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", " ", " " }));

        txtmetrocuadradocomun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmetrocuadradocomunKeyTyped(evt);
            }
        });

        lblmetrocuadradocomun.setText("M² Comun:");

        lblmetrocuadradopropio.setText("M² Propio:");

        txtmetrocuadradopropio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmetrocuadradopropioKeyTyped(evt);
            }
        });

        jLabel3.setText("Edificio:");

        cbotipoedificios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", " ", " " }));

        txtestados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtestadosKeyTyped(evt);
            }
        });

        lblciudad.setText("Ciudad:");

        cbociudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", " ", " " }));

        javax.swing.GroupLayout panelLimpadorClienteLayout = new javax.swing.GroupLayout(panelLimpadorCliente);
        panelLimpadorCliente.setLayout(panelLimpadorClienteLayout);
        panelLimpadorClienteLayout.setHorizontalGroup(
            panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                        .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                                .addComponent(lblnombre1)
                                .addGap(10, 10, 10)
                                .addComponent(txtnombrePropiedads, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                                .addComponent(lbldireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdireccion))
                            .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                                .addComponent(lblmetrocuadradocomun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmetrocuadradocomun, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnumerodepiso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtUsuario1))
                            .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                                .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLimpadorClienteLayout.createSequentialGroup()
                                        .addComponent(lblmetrocuadradopropio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtmetrocuadradopropio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLimpadorClienteLayout.createSequentialGroup()
                                        .addComponent(txtUsuario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtestados)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)))))
                    .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblciudad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbotipropiedad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departamentoCliente, 0, 168, Short.MAX_VALUE)
                    .addComponent(cbotipoedificios, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbociudad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        panelLimpadorClienteLayout.setVerticalGroup(
            panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombrePropiedads, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre1)
                    .addComponent(jLabel2)
                    .addComponent(txtnumerodepiso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departamentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(cbotipropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLimpadorClienteLayout.createSequentialGroup()
                        .addComponent(txtestados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbotipoedificios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtmetrocuadradocomun, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblmetrocuadradocomun)
                        .addComponent(lblmetrocuadradopropio)
                        .addComponent(txtmetrocuadradopropio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLimpadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbociudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblciudad))
                .addGap(66, 66, 66))
        );

        panelComanpropiedad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnmodificarpropiedad.setText("Modificar");
        btnmodificarpropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarpropiedadActionPerformed(evt);
            }
        });

        btnborrarpropiedad.setText("Borrar");
        btnborrarpropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarpropiedadActionPerformed(evt);
            }
        });

        bntagregarpropiedad.setText("Agregar");
        bntagregarpropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntagregarpropiedadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelComanpropiedadLayout = new javax.swing.GroupLayout(panelComanpropiedad);
        panelComanpropiedad.setLayout(panelComanpropiedadLayout);
        panelComanpropiedadLayout.setHorizontalGroup(
            panelComanpropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComanpropiedadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntagregarpropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmodificarpropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnborrarpropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelComanpropiedadLayout.setVerticalGroup(
            panelComanpropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComanpropiedadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComanpropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodificarpropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnborrarpropiedad)
                    .addComponent(bntagregarpropiedad)))
        );

        panelcompropiedad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnguardadPropiedad.setText("Guardar");
        btnguardadPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardadPropiedadActionPerformed(evt);
            }
        });

        btnLimpiarPropiedad.setText("Limpiar");
        btnLimpiarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPropiedadActionPerformed(evt);
            }
        });

        btnCancelarPropiedad.setText("Cancelar");
        btnCancelarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPropiedadActionPerformed(evt);
            }
        });
        btnCancelarPropiedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarPropiedadKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelcompropiedadLayout = new javax.swing.GroupLayout(panelcompropiedad);
        panelcompropiedad.setLayout(panelcompropiedadLayout);
        panelcompropiedadLayout.setHorizontalGroup(
            panelcompropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcompropiedadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnguardadPropiedad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcompropiedadLayout.setVerticalGroup(
            panelcompropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcompropiedadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelcompropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardadPropiedad)
                    .addComponent(btnLimpiarPropiedad)
                    .addComponent(btnCancelarPropiedad))
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(panelLimpadorCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(panelComanpropiedad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(panelcompropiedad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(panelComanpropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelcompropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLimpadorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLimpadorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelComanpropiedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelcompropiedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void CargarTablaPropiedad(List<Propiedad>propiedades){
        DefaultTableModel table = new DefaultTableModel();
        String cabecera[] = {"Codigo","Direccion", "Estado", "MetroCuadradoComun", "MetroCuadradoPropio","Nombre","Numerodepiso","Tipropiedad","Ciudades","Clientes","Edificios"};
        table.setColumnIdentifiers(cabecera);
        Object fila[] = new Object[table.getColumnCount()];

        if (propiedades != null) {
            for (Propiedad e : propiedades) {
                
                fila[0]= e.getCodigo();
                fila[1] = e.getDireccion();
                fila[2]= e.getEstado();
              
                fila[3]= e.getMetroCuadradoComun();
                fila[4]= e.getMetroCuadradoPropio();
                fila[5] = e.getNombre();
                fila[6]= e.getNumerodepiso(); 
                fila[7] = e.getTipropiedad().getTipo();
                fila[8]= e.getCiudades().getNombre();
                fila[9]= e.getClientes().getNombre();
                fila[10]= e.getEdificios().getNombreEdificio();
                
                table.addRow(fila);
            }
            jtablepropiedad.setModel(table);

        }
    
    }
    
    
    public void cargarCombox(List<?> lista, JComboBox combo) {

        DefaultComboBoxModel modelocombo = new DefaultComboBoxModel();
        if (!lista.isEmpty()) {
            modelocombo.addElement(null);
            for (Object o : lista) {
                modelocombo.addElement(o);
            }
            combo.setModel(modelocombo);

        }

    }
    
    
    private void txtnombrePropiedadsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrePropiedadsKeyTyped
     
    }//GEN-LAST:event_txtnombrePropiedadsKeyTyped

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
    
    }//GEN-LAST:event_txtdireccionKeyTyped

    private void txtnumerodepisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumerodepisoKeyTyped
        
    }//GEN-LAST:event_txtnumerodepisoKeyTyped

    private void btnmodificarpropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarpropiedadActionPerformed

        
    }//GEN-LAST:event_btnmodificarpropiedadActionPerformed

    private void btnborrarpropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarpropiedadActionPerformed
  
    }//GEN-LAST:event_btnborrarpropiedadActionPerformed

    private void bntagregarpropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntagregarpropiedadActionPerformed
        String nombre= txtnombrePropiedads.getText();
        String numeropiso = txtnumerodepiso.getText();
        String direccion = txtdireccion.getText();
        String estado = txtestados.getText();
        double  metrocuadradocomun = Double.parseDouble(txtmetrocuadradocomun.getText());
        double  metrocuadradopropio = Double.parseDouble(txtmetrocuadradopropio.getText());
        if(!nombre.equals("")&& !numeropiso.equals("")&& !direccion.equals("")&& !estado.equals("")&& metrocuadradocomun>0 && metrocuadradopropio>0 ){
            
            
            try {
                
             if( departamentoCliente.getSelectedItem() == null && cbociudad.getSelectedItem() ==null && cbotipropiedad.getSelectedItem()== null && cbotipoedificios.getSelectedItem()== null){
               JOptionPane.showMessageDialog(null,"Complete los campos vacio");
               
            }else{
               TipoPropiedad tippropiedad = (TipoPropiedad)cbotipropiedad.getSelectedItem();
               Edificio edi = (Edificio)cbotipoedificios.getSelectedItem();
               Cliente client = (Cliente)departamentoCliente.getSelectedItem();
               Ciudad ciud= (Ciudad)cbociudad.getSelectedItem();
               System.out.println(nombre);
               System.out.println(numeropiso);
               System.out.println(direccion);
               System.out.println(estado);
               System.out.println(tippropiedad);
               System.out.println(edi);
               System.out.println(client);
               System.out.println(ciud);
               System.out.println(metrocuadradocomun);
               System.out.println( metrocuadradopropio);
                this.control.getContraladoraPropiedad().CrearPropiedad(direccion, numeropiso, nombre, estado, metrocuadradopropio, metrocuadradocomun, client, tippropiedad, ciud, edi);
                //this.CargarTablaPropiedad(control.getContraladoraPropiedad().CrearPropiedad(direccion, numeropiso, nombre, estado, metrocuadradopropio, metrocuadradocomun, client, tippropiedad, ciud, edi)getpropiedad();
             }
               
//               
           
//               this.control.getContraladoraPropiedad().CrearPropiedad(direccion, numeropiso, nombre, estado, metrocuadradopropio, metrocuadradocomun, client, tippropiedad, ciud, edi);
//            }  
                
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

//        btnborrarpropiedad.setEnabled(false);
//            
//         try {
//            if(nombre.equals("")|| numeropiso.equals("")|| direccion.equals("")||estado.equals("")|| cbotipropiedad.getSelectedIndex()==0 || cbotipoedificios.getSelectedIndex()==0 || departamentoCliente.getSelectedIndex()==0 || metrocuadradocomun==0 || metrocuadradopropio==0){
//                JOptionPane.showMessageDialog(null,"Complete los campos vacio");
//                
//            }else{
//               TipoPropiedad tippropiedad = (TipoPropiedad)cbotipropiedad.getSelectedItem();
//               Edificio edi = (Edificio)cbotipoedificios.getSelectedItem();
//               Cliente client = (Cliente)departamentoCliente.getSelectedItem();
//               Ciudad ciud= (Ciudad)cbociudad.getSelectedItem();
//               System.out.println("llego");
//               //this.control.getContraladoraPropiedad().crearpro(direccion, numeropiso, nombre, estado, metrocuadradopropio, metrocuadradocomun, client, tippropiedad, edi);
//               this.control.getContraladoraPropiedad().CrearPropiedad(direccion, numeropiso, nombre, estado, metrocuadradopropio, metrocuadradocomun, client, tippropiedad, ciud, edi);
//            }  
//            
//               
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_bntagregarpropiedadActionPerformed

    private void btnguardadPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardadPropiedadActionPerformed
        
    }//GEN-LAST:event_btnguardadPropiedadActionPerformed

    private void btnLimpiarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPropiedadActionPerformed
        
    }//GEN-LAST:event_btnLimpiarPropiedadActionPerformed

    private void btnCancelarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPropiedadActionPerformed

       

    }//GEN-LAST:event_btnCancelarPropiedadActionPerformed

    private void btnCancelarPropiedadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarPropiedadKeyPressed

    }//GEN-LAST:event_btnCancelarPropiedadKeyPressed

    private void txtmetrocuadradocomunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmetrocuadradocomunKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmetrocuadradocomunKeyTyped

    private void txtmetrocuadradopropioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmetrocuadradopropioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmetrocuadradopropioKeyTyped

    private void cbotipropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipropiedadActionPerformed
         
       
    }//GEN-LAST:event_cbotipropiedadActionPerformed

    private void cbotipropiedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbotipropiedadMouseClicked
  
    }//GEN-LAST:event_cbotipropiedadMouseClicked

    private void cbotipropiedadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbotipropiedadItemStateChanged
        
          String sele = cbotipropiedad.getSelectedItem().toString();
        if (sele.equals("Departamento") || sele.equals("departamento")  ) {
            txtmetrocuadradocomun.setVisible(true);
            txtmetrocuadradopropio.setVisible(true);
            lblmetrocuadradocomun.setVisible(true);
            lblmetrocuadradopropio.setVisible(true);
        }else{
            txtmetrocuadradocomun.setVisible(false);
            txtmetrocuadradopropio.setVisible(false);
            lblmetrocuadradocomun.setVisible(false);
            lblmetrocuadradopropio.setVisible(false);
             txtmetrocuadradocomun.setText("");
               txtmetrocuadradopropio.setText("");
        }

    }//GEN-LAST:event_cbotipropiedadItemStateChanged

    private void txtestadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtestadosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntagregarpropiedad;
    private javax.swing.JButton btnCancelarPropiedad;
    private javax.swing.JButton btnLimpiarPropiedad;
    private javax.swing.JButton btnborrarpropiedad;
    private javax.swing.JButton btnguardadPropiedad;
    private javax.swing.JButton btnmodificarpropiedad;
    private javax.swing.JComboBox<String> cbociudad;
    private javax.swing.JComboBox<String> cbotipoedificios;
    private javax.swing.JComboBox<String> cbotipropiedad;
    private javax.swing.JComboBox<String> departamentoCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtablepropiedad;
    private javax.swing.JLabel lblciudad;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblmetrocuadradocomun;
    private javax.swing.JLabel lblmetrocuadradopropio;
    private javax.swing.JLabel lblnombre1;
    private javax.swing.JPanel panelComanpropiedad;
    private javax.swing.JPanel panelLimpadorCliente;
    private javax.swing.JPanel panelcompropiedad;
    private javax.swing.JLabel txtUsuario;
    private javax.swing.JLabel txtUsuario1;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtestados;
    private javax.swing.JTextField txtmetrocuadradocomun;
    private javax.swing.JTextField txtmetrocuadradopropio;
    private javax.swing.JTextField txtnombrePropiedads;
    private javax.swing.JTextField txtnumerodepiso;
    // End of variables declaration//GEN-END:variables
}
